version: '3.8'

services:
  website2:
    build:
      context: .
      dockerfile: Dockerfile
    image: website2:latest
    platform: linux/amd64
    container_name: website2-prod
    ports:
      - '3006:3000'
    environment:
      - NODE_ENV=production
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "const http = require('http'); const options = { hostname: 'localhost', port: 3000, path: '/api/healthcheck', timeout: 3000 }; const req = http.get(options, (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); req.on('error', () => process.exit(1)); req.on('timeout', () => { req.destroy(); process.exit(1); });"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    read_only: false
    mem_limit: 1g
    cpus: '0.5'
