[[edge_handlers]]
  handler = "log_drain"
  filter = "*"

[build.environment]
  LOKI_URL = "https://loki.tools.ejfox.com/loki/api/v1/push"

[build]
  publish = ".output/public"
  command = "npm run build"

# Disable post-processing that might be breaking image loading
[build.processing]
  skip_processing = true

# If you still want some optimizations but not the ones breaking images
# [build.processing]
#   skip_processing = false
#   css.minify = true
#   js.minify = true
#   html.pretty_urls = true
#   images.compress = false  # Disable image compression

# Add headers for Cloudinary resources
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Ensure Cloudinary resources are allowed
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://res.cloudinary.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://umami.tools.ejfox.com;"
