[[edge_handlers]]
  handler = "log_drain"
  filter = "*"

[build.environment]
  LOKI_URL = "https://loki.tools.ejfox.com/loki/api/v1/push"

# Disable post-processing that might be breaking image loading
[build.processing]
  skip_processing = true
