/**
 * apiCatalog — the single source of truth for what the site's API exposes.
 *
 * Consumed by:
 *   - pages/api-docs.vue        (the human-readable Swagger-style page)
 *   - server/routes/openapi.json.ts  (machine-readable OpenAPI 3.1 spec)
 *   - server/api/__tests__/api-catalog.test.ts  (fails if this drifts from the
 *     actual route files on disk — so the docs can never quietly lie)
 *
 * When you add/remove/rename a route, update this array. The test will remind you.
 * See server/README.md for the same information as prose.
 */

export type ApiMethod = 'GET' | 'POST' | 'PATCH'
export type ApiHealth = 'ok' | 'empty-catch' | 'fragile'
/** Who calls it: a page/component, the stats aggregator (direct import), or outside the app. */
export type ApiConsumer = 'frontend' | 'aggregated' | 'external' | 'review'

export interface ApiRoute {
  method: ApiMethod
  /** URL path, e.g. /api/gear/{slug} — dynamic segments in {braces}. */
  path: string
  group: string
  summary: string
  consumer: ApiConsumer
  /** Who/what actually hits it (page name, "stats", "iOS Shortcuts", …). */
  consumedBy: string
  /** Env vars / data files / upstream APIs it needs. */
  deps: string
  health: ApiHealth
  /** Optional note surfaced on the docs page. */
  note?: string
}

export const apiGroups = [
  'Content & blog',
  'Photos & gear',
  'Flashcards',
  'Stats & metrics',
  'Availability & infra',
] as const

export const apiCatalog: ApiRoute[] = [
  // ── Content & blog ─────────────────────────────────────────────────────────
  {
    method: 'GET',
    path: '/api/posts/{slug}',
    group: 'Content & blog',
    summary: 'Blog post by slug (privacy + draft guard)',
    consumer: 'frontend',
    consumedBy: 'pages/blog, projects',
    deps: 'content/processed/*.json',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/manifest',
    group: 'Content & blog',
    summary: 'Published-post manifest (filters draft/hidden/unlisted/pw)',
    consumer: 'frontend',
    consumedBy: 'many pages',
    deps: 'manifest-lite.json',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/projects',
    group: 'Content & blog',
    summary: 'Projects sorted by date',
    consumer: 'frontend',
    consumedBy: 'pages/projects',
    deps: 'manifest + JSON',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/reading',
    group: 'Content & blog',
    summary: 'Books with a random highlight',
    consumer: 'frontend',
    consumedBy: 'pages/reading, now',
    deps: 'content/processed/reading',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/reading/{slug}',
    group: 'Content & blog',
    summary: 'Single book by slug',
    consumer: 'frontend',
    consumedBy: 'pages/reading, now',
    deps: 'reading JSON',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/scraps',
    group: 'Content & blog',
    summary: 'Shared scraps',
    consumer: 'frontend',
    consumedBy: 'pages/threads +5',
    deps: 'Supabase (shared=true)',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/scraps/by-tags',
    group: 'Content & blog',
    summary: 'Scraps matching query tags',
    consumer: 'frontend',
    consumedBy: 'pages/blog, scraps',
    deps: 'Supabase',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/scraps/tags',
    group: 'Content & blog',
    summary: 'All unique scrap tags (sorted, deduped)',
    consumer: 'external',
    consumedBy: 'public API',
    deps: 'Supabase',
    health: 'ok',
    note: 'Tag vocabulary companion to scraps/by-tags; no on-site caller',
  },
  {
    method: 'GET',
    path: '/api/search',
    group: 'Content & blog',
    summary: 'TF-IDF full-text search over posts (?q=&limit=)',
    consumer: 'external',
    consumedBy: 'public API',
    deps: 'content/processed',
    health: 'ok',
    note: 'Returns ranked snippets; no on-site search UI wired yet',
  },
  {
    method: 'GET',
    path: '/api/suggest',
    group: 'Content & blog',
    summary: 'AI tag/summary suggestions for a scrap',
    consumer: 'frontend',
    consumedBy: 'bookmarklet-popup',
    deps: 'blog + Supabase + OpenRouter',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/temporal-context',
    group: 'Content & blog',
    summary: 'Everything around a date',
    consumer: 'frontend',
    consumedBy: 'useTemporalContext',
    deps: 'reading + predictions + Supabase',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/on-this-day',
    group: 'Content & blog',
    summary: 'Historical context by month/day',
    consumer: 'frontend',
    consumedBy: 'pages/on-this-day',
    deps: 'data/on-this-day/*.json',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/changelog',
    group: 'Content & blog',
    summary: 'Git changelog + stats',
    consumer: 'frontend',
    consumedBy: 'pages/changelog',
    deps: 'data/changelog.json',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/robots/{slug}',
    group: 'Content & blog',
    summary: 'AI-readable robot notes',
    consumer: 'frontend',
    consumedBy: 'useProcessedMarkdown',
    deps: 'processed + content/blog/robots',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/wiki',
    group: 'Content & blog',
    summary: 'Personal MediaWiki stats',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'archive.ejfox.com API',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/external-links',
    group: 'Content & blog',
    summary: 'Deduplicated outbound links',
    consumer: 'frontend',
    consumedBy: 'pages/external-links',
    deps: 'data/external_links_final.csv',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/blogroll',
    group: 'Content & blog',
    summary: 'RSS feeds from newsboat config',
    consumer: 'frontend',
    consumedBy: 'pages/following',
    deps: 'data/blogroll.urls',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/webmentions',
    group: 'Content & blog',
    summary: 'Webmentions (moderated)',
    consumer: 'frontend',
    consumedBy: 'Webmentions.vue',
    deps: 'webmention.io + moderation JSON',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/og',
    group: 'Content & blog',
    summary: 'Open Graph metadata fetch',
    consumer: 'frontend',
    consumedBy: 'ReplyContextItem +2',
    deps: 'external HTTP (5-min cache)',
    health: 'ok',
  },
  {
    method: 'POST',
    path: '/api/highlight',
    group: 'Content & blog',
    summary: 'Server-side Shiki syntax highlighting',
    consumer: 'frontend',
    consumedBy: 'GistPreview.vue',
    deps: 'Shiki',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/predictions',
    group: 'Content & blog',
    summary: 'All predictions',
    consumer: 'frontend',
    consumedBy: 'pages/now +6',
    deps: 'content/predictions/*.md',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/predictions/{id}',
    group: 'Content & blog',
    summary: 'One prediction (GET + PATCH write)',
    consumer: 'frontend',
    consumedBy: 'pages/now +6',
    deps: 'content/predictions/*.md',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/calibration',
    group: 'Content & blog',
    summary: 'Prediction Brier scores + accuracy',
    consumer: 'frontend',
    consumedBy: 'useCalibration',
    deps: 'data/calibration-analysis.json',
    health: 'empty-catch',
  },
  {
    method: 'GET',
    path: '/api/words-this-month',
    group: 'Content & blog',
    summary: 'Monthly post/word count',
    consumer: 'aggregated',
    consumedBy: 'blog-stats',
    deps: 'manifest',
    health: 'fragile',
  },

  // ── Photos & gear ──────────────────────────────────────────────────────────
  {
    method: 'GET',
    path: '/api/photos',
    group: 'Photos & gear',
    summary: 'Photo-blog images',
    consumer: 'frontend',
    consumedBy: 'pages/photos',
    deps: 'Cloudinary',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/photo-posts',
    group: 'Photos & gear',
    summary: 'Photo-type posts (no body HTML)',
    consumer: 'frontend',
    consumedBy: 'pages/photos',
    deps: 'manifest + JSON',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/photo-exif',
    group: 'Photos & gear',
    summary: 'Photo EXIF metadata',
    consumer: 'frontend',
    consumedBy: 'pages/photos/[id]',
    deps: 'Cloudinary',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/rides',
    group: 'Photos & gear',
    summary: 'Ride index (GPX-derived tracks + stats)',
    consumer: 'frontend',
    consumedBy: 'pages/rides',
    deps: 'content/processed/rides',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/rides/{slug}',
    group: 'Photos & gear',
    summary: 'One ride: track points, moments, stats',
    consumer: 'frontend',
    consumedBy: 'pages/rides/[slug]',
    deps: 'content/processed/rides',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/gear',
    group: 'Photos & gear',
    summary: 'All gear items',
    consumer: 'frontend',
    consumedBy: 'pages/gear +9',
    deps: 'data/gear.csv',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/gear/{slug}',
    group: 'Photos & gear',
    summary: 'One gear item',
    consumer: 'frontend',
    consumedBy: 'pages/gear/[slug]',
    deps: 'data/gear.csv',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/gear-csv',
    group: 'Photos & gear',
    summary: 'Raw gear CSV export',
    consumer: 'frontend',
    consumedBy: 'pages/gear',
    deps: 'data/gear.csv',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/gear-posts/{slug}',
    group: 'Photos & gear',
    summary: 'Posts tagged with a gear item',
    consumer: 'frontend',
    consumedBy: 'pages/gear/[slug]',
    deps: 'manifest',
    health: 'empty-catch',
  },
  {
    method: 'GET',
    path: '/api/gear-stats',
    group: 'Photos & gear',
    summary: 'Pack weight + item count',
    consumer: 'aggregated',
    consumedBy: 'stats-lite',
    deps: 'data/gear.csv',
    health: 'ok',
  },

  // ── Flashcards ─────────────────────────────────────────────────────────────
  {
    method: 'GET',
    path: '/api/flashcards',
    group: 'Flashcards',
    summary: 'List decks',
    consumer: 'frontend',
    consumedBy: 'pages/flashcards',
    deps: 'public/data/flashcards/*.csv',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/flashcards/{id}',
    group: 'Flashcards',
    summary: 'One deck',
    consumer: 'frontend',
    consumedBy: 'pages/flashcards',
    deps: 'flashcard CSVs',
    health: 'ok',
  },

  // ── Stats & metrics ────────────────────────────────────────────────────────
  {
    method: 'GET',
    path: '/api/stats',
    group: 'Stats & metrics',
    summary: 'Unified stats (17+ sources; imports handlers directly)',
    consumer: 'frontend',
    consumedBy: 'pages/stats, consulting +11',
    deps: 'imports source handlers',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/stats-lite',
    group: 'Stats & metrics',
    summary: 'Tiny stats for iOS Shortcuts / widgets',
    consumer: 'external',
    consumedBy: 'iOS Shortcuts',
    deps: 'imports a subset',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/github',
    group: 'Stats & metrics',
    summary: 'GitHub contributions/commits',
    consumer: 'frontend',
    consumedBy: 'pages/index, stats-lite',
    deps: 'GITHUB_TOKEN',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/github-commits',
    group: 'Stats & metrics',
    summary: 'Pre-cached commit data',
    consumer: 'frontend',
    consumedBy: 'pages/stats',
    deps: 'data/github-commits.json',
    health: 'fragile',
  },
  {
    method: 'GET',
    path: '/api/github-repos-list',
    group: 'Stats & metrics',
    summary: 'Cached repo list',
    consumer: 'frontend',
    consumedBy: 'pages/github/[slug]',
    deps: 'data/github-repos-list.json',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/github/activity',
    group: 'Stats & metrics',
    summary: 'Commit heatmap',
    consumer: 'frontend',
    consumedBy: 'pages/github',
    deps: 'data/github-commits.json',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/gists',
    group: 'Stats & metrics',
    summary: 'Gist list',
    consumer: 'frontend',
    consumedBy: 'pages/gists',
    deps: 'GITHUB_TOKEN',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/gist-stats',
    group: 'Stats & metrics',
    summary: 'Gist language stats',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'calls /api/gists',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/repos/{slug}',
    group: 'Stats & metrics',
    summary: 'One repo detail',
    consumer: 'frontend',
    consumedBy: 'pages/github/[slug]',
    deps: 'GitHub',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/chess',
    group: 'Stats & metrics',
    summary: 'Chess.com ratings',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'CHESS_USERNAME',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/lastfm',
    group: 'Stats & metrics',
    summary: 'Scrobbles / top artists',
    consumer: 'aggregated',
    consumedBy: 'stats-lite',
    deps: 'LASTFM_API_KEY',
    health: 'empty-catch',
  },
  {
    method: 'GET',
    path: '/api/letterboxd',
    group: 'Stats & metrics',
    summary: 'Films watched',
    consumer: 'aggregated',
    consumedBy: 'stats-lite',
    deps: 'RSS',
    health: 'empty-catch',
  },
  {
    method: 'GET',
    path: '/api/goodreads',
    group: 'Stats & metrics',
    summary: 'Books read',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'RSS',
    health: 'empty-catch',
  },
  {
    method: 'GET',
    path: '/api/discogs',
    group: 'Stats & metrics',
    summary: 'Vinyl collection',
    consumer: 'aggregated',
    consumedBy: 'stats-lite',
    deps: 'DISCOGS_TOKEN',
    health: 'empty-catch',
  },
  {
    method: 'GET',
    path: '/api/duolingo',
    group: 'Stats & metrics',
    summary: 'Language streak / XP',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'public API',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/leetcode',
    group: 'Stats & metrics',
    summary: 'Problems solved',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'LeetCode GraphQL',
    health: 'ok',
    note: 'Stale-while-error cache',
  },
  {
    method: 'GET',
    path: '/api/monkeytype',
    group: 'Stats & metrics',
    summary: 'Typing WPM',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'MONKEYTYPE_TOKEN',
    health: 'ok',
    note: 'Disk-cached',
  },
  {
    method: 'GET',
    path: '/api/rescuetime',
    group: 'Stats & metrics',
    summary: 'Productivity time',
    consumer: 'aggregated',
    consumedBy: 'stats-lite',
    deps: 'RESCUETIME_TOKEN',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/apple-health',
    group: 'Stats & metrics',
    summary: 'Health metrics',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'HEALTH_WEBHOOK_SECRET',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/blog-stats',
    group: 'Stats & metrics',
    summary: 'Monthly writing aggregation',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'calls /api/words-this-month',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/reach',
    group: 'Stats & metrics',
    summary: 'Site visitors / pageviews',
    consumer: 'aggregated',
    consumedBy: 'stats',
    deps: 'UMAMI_DATABASE_URL (Postgres)',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/website-stats',
    group: 'Stats & metrics',
    summary: 'Site-wide analytics',
    consumer: 'aggregated',
    consumedBy: 'stats-lite',
    deps: 'UMAMI_DATABASE_URL (Postgres)',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/umami/stats',
    group: 'Stats & metrics',
    summary: 'Per-page views for a URL (?url=)',
    consumer: 'external',
    consumedBy: 'public API',
    deps: 'UMAMI_USERNAME/PASSWORD → umami.tools.ejfox.com',
    health: 'ok',
    note: 'HTTP-API analytics path; parallels the Postgres reach/website-stats',
  },
  {
    method: 'POST',
    path: '/api/umami/auth',
    group: 'Stats & metrics',
    summary: 'Umami access token (HTTP API helper)',
    consumer: 'external',
    consumedBy: 'public API',
    deps: 'UMAMI_USERNAME/PASSWORD → umami.tools.ejfox.com',
    health: 'ok',
    note: 'Auth helper for the HTTP-API analytics path',
  },
  {
    method: 'GET',
    path: '/api/weekly-summary',
    group: 'Stats & metrics',
    summary: 'Per-week aggregate of 9 sources (?week=2026-W05)',
    consumer: 'external',
    consumedBy: 'Sunday Interview skill',
    deps: 'calls github/rescuetime/health/chess/… routes',
    health: 'ok',
  },

  // ── Availability & infra ───────────────────────────────────────────────────
  {
    method: 'GET',
    path: '/api/cal/available-slots',
    group: 'Availability & infra',
    summary: 'Next 3 booking slots',
    consumer: 'frontend',
    consumedBy: 'pages/calendar, consulting, NextAvailableSlot',
    deps: 'CAL_COM_API_KEY',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/cal/availability',
    group: 'Availability & infra',
    summary: 'Quarterly capacity',
    consumer: 'review',
    consumedBy: 'superseded, kept',
    deps: 'CAL_COM_API_KEY',
    health: 'ok',
    note: 'Superseded by available-slots',
  },
  {
    method: 'GET',
    path: '/api/consulting-availability',
    group: 'Availability & infra',
    summary: 'Hand-curated quarterly availability',
    consumer: 'frontend',
    consumedBy: 'pages/consulting',
    deps: 'data/consulting-availability.json',
    health: 'ok',
  },
  {
    method: 'POST',
    path: '/api/webhooks/calcom',
    group: 'Availability & infra',
    summary: 'Booking funnel events (HMAC-verified)',
    consumer: 'external',
    consumedBy: 'Cal.com',
    deps: 'CALCOM_WEBHOOK_SECRET; appends data/calcom-events.jsonl',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/agent/meta',
    group: 'Availability & infra',
    summary: 'API discovery doc for AI agents',
    consumer: 'external',
    consumedBy: 'AI agents',
    deps: 'hardcoded schema',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/agent/timeline',
    group: 'Availability & infra',
    summary: 'Chronological feed for AI agents',
    consumer: 'external',
    consumedBy: 'AI agents',
    deps: 'manifest + predictions + reading',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/healthcheck',
    group: 'Availability & infra',
    summary: 'Uptime / health',
    consumer: 'external',
    consumedBy: 'uptime monitor',
    deps: 'pings /api/manifest',
    health: 'ok',
  },
  {
    method: 'GET',
    path: '/api/build-info',
    group: 'Availability & infra',
    summary: 'Commit hash / build date',
    consumer: 'frontend',
    consumedBy: 'Footer.vue',
    deps: 'baked at build time',
    health: 'ok',
  },
]
