name: Process Markdown and Auto-Toot

on:
  push:
    branches:
      - main
    paths:
      - 'content/**/*.md'  # Only run on markdown file changes
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'content/**/*.md'  # Only run on markdown file changes

jobs:
  process-and-toot:
    runs-on: ubuntu-latest
    # Don't run on PRs from forks for security
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last two commits for diff

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Cache content hash
        uses: actions/cache@v2
        with:
          path: cache/content-hash-cache.json
          key: ${{ runner.os }}-content-hash-${{ hashFiles('content/**/*.md') }}
          restore-keys: |
            ${{ runner.os }}-content-hash-

      - name: Process Markdown
        run: node scripts/processMarkdown.mjs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

      - name: Auto-Toot
        run: node scripts/autoToot.mjs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content cache
          git commit -m "chore: process markdown and auto-toot" || echo "No changes to commit"

      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push
